BROWSER:
  TYPE: chrome
#  BROWSER_BINARY_PATH: <path_name_of_browser_binary>
#  BROWSER_DRIVER_PATH: /Users/nyon/automation/webdriver/chromedriver/chromedriver
  HEADLESS: False
#  WINDOW_SIZE: "1920,1080"  #Recommended 1920,1080
#  BROWSER_ARGUMENTS:
#    no-sandbox
#    arg2=xyz

WEB_URL: https://www.gobear.com/ph?x_session_type=UAT

#DEFAULT_USERNAME: ntnhon@gmail.com
#DEFAULT_PASSWORD: 12345678x@X
#USER_NAME: Nyon Nguyen